project:
  type: book

book:
  title: "Phylogenetic Comparative Methods in R - Solutions"
  date: "2023"
  chapters:
    - index.qmd
    - chapters/chapter_01.qmd
    - chapters/chapter_02.qmd
    - chapters/chapter_03.qmd
    - chapters/chapter_04.qmd
    - chapters/chapter_05.qmd
    - chapters/chapter_06.qmd
    - chapters/chapter_07.qmd
    - chapters/chapter_08.qmd
    - chapters/chapter_09.qmd
    - chapters/chapter_10.qmd
    - chapters/chapter_11.qmd
    - chapters/chapter_12.qmd
    - chapters/chapter_13.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: 
  mode: source